services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 -t public
    volumes:
      - .:/var/www/html
